import './globals.css'
import 'bootstrap/dist/css/bootstrap.css'
import { Inter } from 'next/font/google'
import Header from '@/Components/Desktop/Header/Header'
import Navbar from '@/Components/Desktop/Navbar/Navbar'
import CarSearch from '@/Components/Desktop/Car Search/CarSearch'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        
      <Header />
      <Navbar />
      <CarSearch />
        {children}
        
        </body>
    </html>
  )
}
